### ISSUE TITLE
Multiple GRPC endpoints

### ISSUE THREAD

**Issue by abdulgig** [staketown/oracle-exporter#1]
Can we add multiple GRPC endpoints to the config or we need essentially spin up a new container for that purpose? @mogoll92 ?

**Comment by mogoll92** [comment]
> Can we add multiple GRPC endpoints to the config or we need essentially spin up a new container for that purpose? @mogoll92 ?

Hi, what's purpose for? I guess for tracking several validators on the same dashboard. As initially it was developed for individual validator's purpose there is no such possibility at that moment. 

We could add that feature. After that all what will be needed is to spin up new container that will be responsible to gather statistic for validator and add config for new validator to prometheus.

**Comment by robert-zaremba** [comment]
> I guess for tracking several validators on the same dashboard. 

Exactly. We run few internal validators for our testnets, and would be great if we can have one dashboard. Thanks!

**Comment by mogoll92** [comment]
> > I guess for tracking several validators on the same dashboard.
> 
> Exactly. We run few internal validators for our testnets, and would be great if we can have one dashboard. Thanks!

okay, in this case just need to update dashboard, we will do this. After that yo don't need to spin up several umee exporters, just need to add several validators to prometheus and only one umee exporter container will be needed.
It will be like this with manual selecting validator over drop-down to display stats.
<img width="1432" alt="Screenshot 2023-12-11 at 13 02 28" src="https://github.com/staketown/oracle-monitoring/assets/16834384/aa0f1c9f-c905-4f75-a151-45327bf0453c">

**Comment by mogoll92** [comment]
> > I guess for tracking several validators on the same dashboard.
> 
> Exactly. We run few internal validators for our testnets, and would be great if we can have one dashboard. Thanks!

We have updated dashboard and added instructions what should be done to support several validators here:
https://github.com/staketown/oracle-monitoring?tab=readme-ov-file#support-several-validator

**Comment by abdulgig** [comment]
Awesome 👌  !!

**Comment by mogoll92** [comment]
I close this issue as possibility has been added and no other questions on that.
